In [ ]:
#import tensorflow

import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check number of dimensions of the tensor

scalar.ndim

0

In [ ]:
#Create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check dimensions of vector
vector.ndim

1

In [ ]:
#Create a matrix (has > 1 dimension)

matrix = tf.constant([
    [10,7],
    [7,10]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#matrix no. of dims

matrix.ndim

2

In [ ]:
another_matrix = tf.constant([
    [10.,7.],
    [3.,2.],
    [9.,7.]
],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 9.,  7.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Create a tensor

tensor = tf.constant([
    [
        [7,8,5],
        [6,9,7]
    ],
    [
        [4,3,1],
        [2,6,9]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[7, 8, 5],
        [6, 9, 7]],

       [[4, 3, 1],
        [2, 6, 9]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
#Create a tensor with tf.variable()

ct = tf.Variable([10,7])
ut = tf.constant([10,7])

ct,ut

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
ct[1].assign(10)
ct

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
ut[1].assign(10)
ut

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
#Random tensors

r1 = tf.random.Generator.from_seed(12)
r1 = r1.normal(shape=(3,2))
r1
r2 = tf.random.Generator.from_seed(12)
r2 = r2.normal(shape=(3,2))
r2

r1, r2, r1==r2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
t1 = tf.constant([
    [3,2],
    [2,5],
    [10,7]
])
t1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  2],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #Global-level seed
tf.random.shuffle(t1, seed = 42)  #Operational-level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  2],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.ones(shape=(3,2,5))

<tf.Tensor: shape=(3, 2, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros(shape = (4,2,3))

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
#Creating tensors from numpy arrays

import numpy as np

a = np.arange(1,25,dtype = np.int32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tf.constant(a)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
tf.constant(a,shape = (2,4,3))

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [ ]:
#get attributes of a tensor

t1.shape
t1.ndim
tf.size(t1).numpy()
t1.shape[0]
t1.shape[-1]

2

In [ ]:
#Tensor Indexing

random_list = [3,5,9,12]
random_list[-1]

12

In [ ]:
random_tensor = tf.constant(
                [[10,7],
                 [3,2]]
                )
random_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2]], dtype=int32)>

In [ ]:
random_tensor[:2,:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2]], dtype=int32)>

In [ ]:
#tf.newaxis
random_tensor2 = random_tensor[...,tf.newaxis]
random_tensor2

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 2]]], dtype=int32)>

In [ ]:
#alternative to tf.newaxis

tf.expand_dims(random_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  2]]], dtype=int32)>

In [ ]:
#Tensors manipulation

random_tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  20]], dtype=int32)>

In [ ]:
tf.multiply(random_tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  20]], dtype=int32)>

In [ ]:
#Converting dtype of tensors. By default they are in 32-bit precision which takes longer to run, 16-bit precision runs much faster using accelerators.

t = tf.constant([10,7,8,2])
t

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10,  7,  8,  2], dtype=int32)>

In [ ]:
tf.cast(t,dtype='int16')

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([10,  7,  8,  2], dtype=int16)>

In [ ]:
t1 = tf.constant([
    [1.56,2.07],
    [3.69,4.76]
])
t1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.56, 2.07],
       [3.69, 4.76]], dtype=float32)>

In [ ]:
tf.cast(t1,dtype = 'float16')

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1.56, 2.07],
       [3.69, 4.76]], dtype=float16)>

In [ ]:
#Aggregation

t1 = tf.constant([
    [1.56,2.07],
    [3.69,4.76]
])
tf.reduce_mean(t1)


<tf.Tensor: shape=(), dtype=float32, numpy=3.02>

In [ ]:
import tensorflow_probability as tfp

tfp.stats.percentile(t1, q = 30)

<tf.Tensor: shape=(), dtype=float32, numpy=2.07>

In [ ]:
tf.math.reduce_variance(t1)

<tf.Tensor: shape=(), dtype=float32, numpy=1.6276503>

In [ ]:
tf.math.reduce_std(t1)

<tf.Tensor: shape=(), dtype=float32, numpy=1.275794>

In [ ]:
#Positional max and min

tf.random.set_seed(77)
t2 = tf.random.uniform([50])
t2

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.07212555, 0.5266396 , 0.72306037, 0.35061193, 0.8296379 ,
       0.11147892, 0.457646  , 0.16073549, 0.84786737, 0.96440816,
       0.31061685, 0.10325825, 0.8765378 , 0.7888309 , 0.39391422,
       0.464728  , 0.38612247, 0.5357307 , 0.3301475 , 0.22967815,
       0.17843282, 0.64866376, 0.35661578, 0.58480024, 0.9027157 ,
       0.70363975, 0.9455031 , 0.5759568 , 0.32488906, 0.93933237,
       0.18535316, 0.9726256 , 0.46691728, 0.6460202 , 0.7892866 ,
       0.6747252 , 0.8288157 , 0.05637586, 0.00927389, 0.5812448 ,
       0.96447814, 0.7342422 , 0.59657824, 0.876703  , 0.8870752 ,
       0.85794044, 0.47055292, 0.28132105, 0.6987431 , 0.0160569 ],
      dtype=float32)>

In [ ]:
tf.argmax(t2)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [ ]:
assert t2[tf.argmax(t2)] == tf.reduce_max(t2)

In [ ]:
t = tf.random.uniform(shape = (1,1,1,1,3),seed = 10)
tf.squeeze(t)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.14155996, 0.26850533, 0.384063  ], dtype=float32)>

In [ ]:
#One hot encoding
l = tf.constant([3,4,7,6])
tf.one_hot(l, depth=8)

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>

In [ ]:
#Tensorflow and NumPy
import numpy as np
import tensorflow as tf

t3 = tf.constant([4,7,8,9])
t4 = tf.constant(np.array([4,7,4,2,9]))
t3, t4

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 7, 4, 2, 9])>)

In [ ]:
tf.config.list_physical_devices(device_type='GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Feb 14 05:24:39 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0              32W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
r = tf.random.uniform(shape=(224,224,3))
r

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.48379457, 0.9415177 , 0.56065977],
        [0.8886999 , 0.74753225, 0.88167346],
        [0.7334715 , 0.64509654, 0.7498077 ],
        ...,
        [0.54924285, 0.5941911 , 0.6261028 ],
        [0.45896494, 0.7299032 , 0.5461794 ],
        [0.45415533, 0.70303285, 0.3385291 ]],

       [[0.7108761 , 0.03199506, 0.00297415],
        [0.5442922 , 0.8149636 , 0.36924493],
        [0.11179793, 0.08235288, 0.92424726],
        ...,
        [0.61802006, 0.25036347, 0.7841723 ],
        [0.28380454, 0.26931393, 0.86035764],
        [0.78229415, 0.6474621 , 0.72700727]],

       [[0.41202724, 0.76705647, 0.06173384],
        [0.35794592, 0.9660964 , 0.49721694],
        [0.44236648, 0.10612142, 0.51990974],
        ...,
        [0.46173823, 0.5076922 , 0.41455853],
        [0.68372214, 0.15525246, 0.95599115],
        [0.04465914, 0.6459093 , 0.02407372]],

       ...,

       [[0.4735186 , 0.6211252 , 0.31603217],
        [0.75

In [ ]:
s = tf.random.uniform(shape=(10,))
s

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.1176343 , 0.6994983 , 0.7866379 , 0.08108675, 0.06909537,
       0.8556292 , 0.5506996 , 0.85884094, 0.34368002, 0.92529774],
      dtype=float32)>